package com.vedant.krail.model

data class Stations(
    val name: String,
    val isBig: Boolean
)

val stations = listOf(
    Stations("Roha", true),
    Stations("Kolad", false),
    Stations("Indapur", false),
    Stations("Mangaon", false),
    Stations("Goregaon Road", false),
    Stations("Veer", false),
    Stations("Sape Wamane", false),
    Stations("Karanjadi", false),
    Stations("Vinhere", false),
    Stations("Diwankhavati", false),
    Stations("Kalambani Budruk", false),
    Stations("Khed", false),
    Stations("Anjani", false),
    Stations("Chiplun", true),
    Stations("Kamathe", false),
    Stations("Sawarda", false),
    Stations("Aravali Road", false),
    Stations("Kadavai", false),
    Stations("Sangameshwar Road", false),
    Stations("Ukshi", false),
    Stations("Bhoke", false),
    Stations("Ratnagiri", true),
    Stations("Nivasar", false),
    Stations("Adavali", false),
    Stations("Veravali", false),
    Stations("Vilavade", false),
    Stations("Rajapur Road", false),
    Stations("Kharepatan Road", false),
    Stations("Vaibhavwadi Road", false),
    Stations("Achirne", false),
    Stations("Nandgaon Road", false),
    Stations("Kankavli", false),
    Stations("Sindhudurg", false),
    Stations("Kudal", true),
    Stations("Zarap", false),
    Stations("Sawantwadi Road", false),
    Stations("Madure", false),
    Stations("Pernem", false),
    Stations("Thivim", false),
    Stations("Karmali", false),
    Stations("Verna", false),
    Stations("Majorda Jn", false),
    Stations("Madgaon Jn", true),
    Stations("Balli", false),
    Stations("Canacona", false),
    Stations("Loliem", false),
    Stations("Asnoti", false),
    Stations("Karwar", true),
    Stations("Harwada", false),
    Stations("Ankola", false),
    Stations("Gokarna Road", false),
    Stations("Mirjan", false),
    Stations("Kumta", false),
    Stations("Honnavar", false),
    Stations("Manki", false),
    Stations("Murdeshwar", false),
    Stations("Chitrapur", false),
    Stations("Bhatkal", true),
    Stations("Shiroor", false),
    Stations("Mookambika Road Byndoor Halt", false),
    Stations("Bijoor", false),
    Stations("Senapura", false),
    Stations("Kundapura", false),
    Stations("Barkur", false),
    Stations("Udupi", true),
    Stations("Innanje", false),
    Stations("Padubidri", false),
    Stations("Nandikoor", false),
    Stations("Mulki", false),
    Stations("Surathkal", false),
    Stations("Thokur",true)
)

